name = "sarkari-paper-api"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Optional: override default SEO base URL
# BASE_URL = "https://sarkaripaper.com"
